// Static data for the rule-based workout generator (no AI)

export const EXERCISES: string[] = [
  'Thrusters',
  'Pull-ups',
  'Push-ups',
  'Burpees',
  'Box Jumps',
  'Box Jump Overs',
  'Wall Balls',
  'Kettlebell Swings',
  'Double-unders',
  'Single-unders',
  'Jump Rope',
  'Toes-to-Bar',
  'Knee Raises',
  'Hanging Knee Raises',
  'Handstand Push-ups',
  'Pike Push-ups',
  'Push Press',
  'Strict Press',
  'Power Cleans',
  'Squat Cleans',
  'Clean and Jerk',
  'Snatch',
  'Power Snatch',
  'Overhead Squat',
  'Front Squat',
  'Back Squat',
  'Deadlift',
  'Sumo Deadlift High Pull',
  'Lunges',
  'Walking Lunges',
  'Running',
  'Row (Concept2)',
  'Bike (Assault/ Echo)',
  'Ski Erg',
  'Ring Rows',
  'Ring Dips',
  'Bar Muscle-ups',
  'Ring Muscle-ups',
  'Pistols',
  'Sit-ups',
  'V-ups',
  'AbMat Sit-ups',
  'GHD Sit-ups',
  'Back Extensions',
  'Devil Press',
  'Dumbbell Snatch',
  'Dumbbell Thrusters',
  'Dumbbell Box Step-overs',
  'Calorie Row',
  'Calorie Bike',
  'Wall Walks',
  'Bear Crawl',
  'Sandbag Cleans',
  'Rope Climbs',
];

export const STRENGTH_PRESETS: { label: string; value: string }[] = [
  { label: 'Back Squat 5x5', value: 'Back Squat 5x5' },
  { label: 'Deadlift 3x5', value: 'Deadlift 3x5' },
  { label: 'Strict Press 5-5-5', value: 'Strict Press 5-5-5' },
  { label: 'Front Squat 5x3', value: 'Front Squat 5x3' },
  { label: 'Power Clean 5x3', value: 'Power Clean 5x3' },
  { label: 'Snatch 5x2', value: 'Snatch 5x2' },
  { label: 'Custom', value: '' },
];

export const DURATION_PRESETS = [20, 30, 35, 45, 60] as const;

export const WORKOUT_FORMATS = [
  { value: 'AMRAP', label: 'AMRAP' },
  { value: 'For Time', label: 'For Time' },
  { value: 'EMOM', label: 'EMOM' },
  { value: 'Rounds', label: 'Rounds' },
] as const;

export type WorkoutFormat = (typeof WORKOUT_FORMATS)[number]['value'];
